### PR TITLE
Hardcode akka 2.5 version in 2.5 branch

### PR DESCRIPTION
**Pull request by chbatey**
Oherwise the 2.5 branch picks up 2.6 and has mixed dependencies

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Review by raboof — APPROVED** [review]

**Comment by raboof** [comment]
refs #17

**Comment by patriknw** [comment]
In what more places do we need to do the same?

**Comment by chbatey** [comment]
any gitter8 template that we have not ported to 2.6

**Comment by raboof** [comment]
I think I fixed up most of those as their travis jobs were failing ;) - but good to double-check

**Pull request merged**
